extends CipheredSignal

class_name CipheredText

var source: String = "Placeholder":
	set(new_source):
		source = new_source
		_reset()
		_render()

var _transformed_text: String = ""

func _reset() -> void:
	var prng = RandomNumberGenerator.new()
	prng.seed = source.hash()

	# "Zero values" means that the text is unfiltered. We want to ensure to have strictly 10% of slider value as zero values.
	const ZERO_VALUE_TARGET_COUNT: int = int(SignalInput.N_VALUES / 10.0)

	# Regenerate the rot possibilities
	_rot_values.clear()
	for i in range(SignalInput.N_VALUES):
		_rot_values.append(i % 26)
	Utils.shuffle_with_prng(_rot_values, prng)

	# Regenerate the splits possibilities
	_word_shuffle_n_splits.clear()
	var source_n_words: int = source.split(" ").size()
	var max_splits: int = int(log(source_n_words) / log(2))

	# Fill zero values
	for i in range(ZERO_VALUE_TARGET_COUNT):
		_word_shuffle_n_splits.append(0)
	while _word_shuffle_n_splits.size() < SignalInput.N_VALUES:
		# All the zero values are pre-filled
		var min_split = 1
		var i_split = prng.randi_range(min_split, max_splits)
		_word_shuffle_n_splits.append(i_split)
	
	# Shuffle the splits because of the pre inserted zeroes
	Utils.shuffle_with_prng(_word_shuffle_n_splits, prng)

	# Regenerate the space shuffle possibilities
	_space_shuffle_values.clear()

	# Fill zero values
	for i in range(ZERO_VALUE_TARGET_COUNT):
		_space_shuffle_values.append(0)
	while _space_shuffle_values.size() < SignalInput.N_VALUES:
		# All the zero values are pre-filled
		var frequency = prng.randf_range(0 + SignalInput.STEP, 1.0)
		_space_shuffle_values.append(frequency)
		
	# Shuffle the splits because of the pre inserted zeroes
	Utils.shuffle_with_prng(_space_shuffle_values, prng)

# MARK: ROT

@export var rot_input: SignalInput
var _rot_values: Array[int] = []

# Index of the rotation in _rot_values
var letter_rot_index: int = 0: 
	get(): return letter_rot_index
	set(rot_index):
		letter_rot_index = rot_index
		_render()

func _rot_input_changed(value: float) -> void:
	var idx = int(value * _rot_values.size()) % _rot_values.size()
	letter_rot_index = idx

# Generated by Claude
func _rot_n(text: String, slider_index: int) -> String:
	assert(_rot_values.size() > 0)
	var shift = _rot_values[slider_index % _rot_values.size()]

	shift = ((shift % 26) + 26) % 26  # normalize: handles negatives & >25
	var result = ""
	for ch in text:
		var code = ch.unicode_at(0)
		if code >= 65 and code <= 90:    # A-Z
			result += char(65 + (code - 65 + shift) % 26)
		elif code >= 97 and code <= 122: # a-z
			result += char(97 + (code - 97 + shift) % 26)
		else:
			result += ch
	return result

# MARK: Words shuffle

@export var word_shuffle_input: SignalInput

# Index of the shuffle in _word_shuffle_n_splits
var words_shuffle_index = 0: 
	get(): return words_shuffle_index
	set(words_shuffle_index_value):
		words_shuffle_index = words_shuffle_index_value
		_render()

var _word_shuffle_n_splits: Array[int] = []

func _word_shuffle_input_changed(value: float) -> void:
	var idx = int(value * _word_shuffle_n_splits.size()) % _word_shuffle_n_splits.size()
	words_shuffle_index = idx

func _shuffle_words(text: String, slider_index: int) -> String:
	assert(_word_shuffle_n_splits.size() > 0)
	var n_splits = _word_shuffle_n_splits[slider_index % _word_shuffle_n_splits.size()]
		
	if n_splits == 0:
		return text
	assert(n_splits > 0)

	# Ensures that we always have the same splits by controlling the seed
	var prng = RandomNumberGenerator.new()
	prng.seed = source.hash() + slider_index

	var words = text.split(" ")

	var i_splits: Array[int] = []
	while i_splits.size() < n_splits:
		var new_split = prng.randi_range(1, words.size() - 1)
		# Avoid duplicates
		if new_split not in i_splits:
			i_splits.append(new_split)
	i_splits.sort()

	# Cut in segments
	var segments: Array[String] = []
	var prev = 0
	for idx in i_splits:
		segments.append(" ".join(words.slice(prev, idx)))
		prev = idx
	segments.append(" ".join(words.slice(prev, words.size())))

	Utils.shuffle_with_prng(segments, prng)

	return " ".join(segments)

# MARK: Space shuffle

@export var space_shuffle_input: SignalInput

var _space_shuffle_values: Array[int] = []

# Index of the shuffle in _space_shuffle_values
var space_shuffle_index = 0: 
	get(): return space_shuffle_index
	set(space_shuffle_index_value):
		space_shuffle_index = space_shuffle_index_value
		_render()

func _space_shuffle_input_changed(value: float) -> void:
	var idx = int(value * _space_shuffle_values.size()) % _space_shuffle_values.size()
	space_shuffle_index = idx

func _shuffle_spaces(text: String, slider_index: int) -> String:
	assert(_space_shuffle_values.size() > 0)
	var shuffle_frequency = _space_shuffle_values[slider_index % _space_shuffle_values.size()]

	var prng = RandomNumberGenerator.new()
	prng.seed = source.hash() + slider_index

	var spaces_to_move: int = 0

	var chars = text.split("")
	for i in range(chars.size()):
		if chars[i] == " " and prng.randf() < shuffle_frequency:
			chars[i] = ""
			spaces_to_move += 1
	
	for i in range(spaces_to_move):
		var insert_pos = prng.randi_range(0, chars.size())
		chars.insert(insert_pos, " ")
	return "".join(chars)

# MARK: Common

func _ready() -> void:
	rot_input.signal_input_changed.connect(_rot_input_changed)
	word_shuffle_input.signal_input_changed.connect(_word_shuffle_input_changed)
	space_shuffle_input.signal_input_changed.connect(_space_shuffle_input_changed)
	_reset()
	_render()

func _render():
	# Apply rot25
	_transformed_text = _rot_n(source, letter_rot_index)
	
	# Apply word shuffle
	_transformed_text = _shuffle_words(_transformed_text, words_shuffle_index)

	# Apply space shuffle
	_transformed_text = _shuffle_spaces(_transformed_text, space_shuffle_index)

	super()

func get_transformed_text() -> String:
	return _transformed_text
