extends CipheredSignal

class_name CipheredText

var source: String = "Salut les amis ! Ca farte ?"
var _transformed_text: String = ""

# MARK: ROT

@export var rot_input: SignalInput
var _rot_scale: int = 25
var _rot_random_offset: int = randi() % _rot_scale

var letter_rot: int = 0: 
	get(): return letter_rot
	set(rot):
		letter_rot = rot
		_render()

func _rot_input_changed(value: float) -> void:
	var rot_value = int(value * _rot_scale + _rot_random_offset) % _rot_scale
	letter_rot = rot_value
	print("Rot input: {value} new value {rot_value}".format({"value": value, "rot_value": rot_value}))

# Generated by Claude
func _rot_n(text: String, shift: int) -> String:
	shift = ((shift % 26) + 26) % 26  # normalize: handles negatives & >25
	var result = ""
	for ch in text:
		var code = ch.unicode_at(0)
		if code >= 65 and code <= 90:    # A-Z
			result += char(65 + (code - 65 + shift) % 26)
		elif code >= 97 and code <= 122: # a-z
			result += char(97 + (code - 97 + shift) % 26)
		else:
			result += ch
	return result

# MARK: Words shuffle

@export var words_shuffle_input: SignalInput
var _words_shuffle_random_offset: float = randf()

var words_shuffle = 0: 
	get(): return words_shuffle
	set(words_shuffle_value):
		words_shuffle = words_shuffle_value
		_render()

func _words_shuffle_input_changed(value: float) -> void:
	var source_n_words: int = source.split(" ").size()
	var max_splits: int = int(log(source_n_words) / log(2))

	var words_shuffle_value = int((value + _words_shuffle_random_offset) * max_splits) % max_splits
	words_shuffle = words_shuffle_value

func _shuffle_words(text: String, n_splits: int) -> String:
	if n_splits == 0:
		return text
	assert(n_splits > 0)

	# Ensures that we always have the same splits by controlling the seed
	var prng = RandomNumberGenerator.new()
	prng.seed = source.hash() + n_splits

	var words = text.split(" ")

	var i_splits: Array[int] = []
	while i_splits.size() < n_splits:
		var new_split = prng.randi_range(1, words.size() - 1)
		# Avoid duplicates
		if new_split not in i_splits:
			i_splits.append(new_split)
	i_splits.sort()

	# Cut in segments
	var segments: Array[String] = []
	var prev = 0
	for idx in i_splits:
		segments.append(" ".join(words.slice(prev, idx)))
		prev = idx
	segments.append(" ".join(words.slice(prev, words.size())))

	# Cannot use shuffle() here because of custom PRNG
	for i in range(segments.size() - 1, 0, -1):
		var j = prng.randi_range(0, i)
		var temp = segments[i]
		segments[i] = segments[j]
		segments[j] = temp

	return " ".join(segments)

# MARK: Common

func _ready() -> void:
	rot_input.signal_input_changed.connect(_rot_input_changed)
	words_shuffle_input.signal_input_changed.connect(_words_shuffle_input_changed)
	_render()

func _render():
	# Apply rot25
	_transformed_text = _rot_n(source, letter_rot)
	
	# Apply words shuffle
	_transformed_text = _shuffle_words(_transformed_text, words_shuffle)

	super()

func get_transformed_text() -> String:
	return _transformed_text
