extends CipheredSignal

class_name CipheredText

var source: String = "Salut les amis ! Ca farte ?":
	set(new_source):
		source = new_source
		_reset()
		_render()

var _transformed_text: String = ""

func _reset() -> void:
	var prng = RandomNumberGenerator.new()
	prng.seed = source.hash()

	# "Zero values" means that the text is unfiltered. We want to ensure to have strictly 10% of slider value as zero values.
	const ZERO_VALUE_TARGET_COUNT: int = int(SignalInput.N_VALUES / 10.0)

	# Regenerate the rot possibilities
	_rot_values.clear()
	for i in range(SignalInput.N_VALUES):
		_rot_values.append(i % 26)
	Utils.shuffle_with_prng(_rot_values, prng)

	# Regenerate the splits possibilities
	_word_shuffle_n_splits.clear()
	var source_n_words: int = source.split(" ").size()
	var max_splits: int = int(log(source_n_words) / log(2))
	var zero_value_count: int = 0
	for i in range(SignalInput.N_VALUES):
		# Target count of zero values matched
		var min_split = 0 if zero_value_count >= ZERO_VALUE_TARGET_COUNT else 1
		var i_split = prng.randi_range(min_split, max_splits)
		if i_split == 0:
			zero_value_count += 1

		_word_shuffle_n_splits.append(i_split)

	# Regenerate the space shuffle possibilities
	_space_shuffle_values.clear()
	zero_value_count = 0
	for i in range(SignalInput.N_VALUES):
		var min_split = 0 if zero_value_count >= ZERO_VALUE_TARGET_COUNT else 1

		var i_split = prng.randi_range(min_split, max_splits)
		_space_shuffle_values.append(i_split)
		if i_split == 0:
			zero_value_count += 1

# MARK: ROT

@export var rot_input: SignalInput
var _rot_values: Array[int] = []

var letter_rot: int = 0: 
	get(): return letter_rot
	set(rot):
		letter_rot = rot
		_render()

func _rot_input_changed(value: float) -> void:
	assert(_rot_values.size() > 0)
	var rot_value = _rot_values[int(value * _rot_values.size()) % _rot_values.size()]
	letter_rot = rot_value

# Generated by Claude
func _rot_n(text: String, shift: int) -> String:
	shift = ((shift % 26) + 26) % 26  # normalize: handles negatives & >25
	var result = ""
	for ch in text:
		var code = ch.unicode_at(0)
		if code >= 65 and code <= 90:    # A-Z
			result += char(65 + (code - 65 + shift) % 26)
		elif code >= 97 and code <= 122: # a-z
			result += char(97 + (code - 97 + shift) % 26)
		else:
			result += ch
	return result

# MARK: Words shuffle

@export var word_shuffle_input: SignalInput

var words_shuffle = 0: 
	get(): return words_shuffle
	set(words_shuffle_value):
		words_shuffle = words_shuffle_value
		_render()

var _word_shuffle_n_splits: Array[int] = []

func _word_shuffle_input_changed(value: float) -> void:
	assert(_word_shuffle_n_splits.size() > 0)

	var idx = int(value * _word_shuffle_n_splits.size()) % _word_shuffle_n_splits.size()
	var words_shuffle_value = _word_shuffle_n_splits[idx]
	words_shuffle = words_shuffle_value

func _shuffle_words(text: String, n_splits: int) -> String:
	if n_splits == 0:
		return text
	assert(n_splits > 0)

	# Ensures that we always have the same splits by controlling the seed
	var prng = RandomNumberGenerator.new()
	prng.seed = source.hash() + n_splits

	var words = text.split(" ")

	var i_splits: Array[int] = []
	while i_splits.size() < n_splits:
		var new_split = prng.randi_range(1, words.size() - 1)
		# Avoid duplicates
		if new_split not in i_splits:
			i_splits.append(new_split)
	i_splits.sort()

	# Cut in segments
	var segments: Array[String] = []
	var prev = 0
	for idx in i_splits:
		segments.append(" ".join(words.slice(prev, idx)))
		prev = idx
	segments.append(" ".join(words.slice(prev, words.size())))

	Utils.shuffle_with_prng(segments, prng)

	return " ".join(segments)

# MARK: Space shuffle

@export var space_shuffle_input: SignalInput

var _space_shuffle_values: Array[int] = []

var space_shuffle = 0: 
	get(): return space_shuffle
	set(space_shuffle_value):
		space_shuffle = space_shuffle_value
		_render()

func _space_shuffle_input_changed(value: float) -> void:
	assert(_space_shuffle_values.size() > 0)

	var idx = int(value * _space_shuffle_values.size()) % _space_shuffle_values.size()
	var space_shuffle_value = _space_shuffle_values[idx]
	space_shuffle = space_shuffle_value

func _shuffle_spaces(text: String, shuffle_frequency: float) -> String:
	var prng = RandomNumberGenerator.new()
	prng.seed = source.hash() + shuffle_frequency

	var spaces_to_move: int = 0

	var chars = text.split("")
	for i in range(chars.size()):
		if chars[i] == " " and prng.randf() < shuffle_frequency:
			chars[i] = ""
			spaces_to_move += 1
	
	for i in range(spaces_to_move):
		var insert_pos = prng.randi_range(0, chars.size())
		chars.insert(insert_pos, " ")
	return "".join(chars)

# MARK: Common

func _ready() -> void:
	rot_input.signal_input_changed.connect(_rot_input_changed)
	word_shuffle_input.signal_input_changed.connect(_word_shuffle_input_changed)
	space_shuffle_input.signal_input_changed.connect(_space_shuffle_input_changed)
	_reset()
	_render()

func _render():
	# Apply rot25
	_transformed_text = _rot_n(source, letter_rot)
	
	# Apply word shuffle
	_transformed_text = _shuffle_words(_transformed_text, words_shuffle)

	# Apply space shuffle
	_transformed_text = _shuffle_spaces(_transformed_text, space_shuffle)

	super()

func get_transformed_text() -> String:
	return _transformed_text
